/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giao_dien;

/**
 *
 * @author FPTSHOP
 */
public class dangKy extends javax.swing.JFrame {

    /**
     * Creates new form signIn
     */
    public dangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundSignIn = new javax.swing.JPanel();
        rightSignIn = new javax.swing.JPanel();
        signInText = new javax.swing.JLabel();
        tkTextSignIn = new javax.swing.JLabel();
        inputtkSignIn = new javax.swing.JTextField();
        mkTextSignIn = new javax.swing.JLabel();
        inputxnSignIn = new javax.swing.JTextField();
        xnTextSignIn = new javax.swing.JLabel();
        inputmkSignIn = new javax.swing.JTextField();
        msnvTextSignIn = new javax.swing.JLabel();
        inputmsnvSignIn = new javax.swing.JTextField();
        inputsdtSignIn = new javax.swing.JTextField();
        sdtTextSignIn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        inputsdtSignIn1 = new javax.swing.JTextField();
        sdtTextSignIn1 = new javax.swing.JLabel();
        leftSignIn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundSignIn.setPreferredSize(new java.awt.Dimension(800, 500));
        backgroundSignIn.setLayout(null);

        rightSignIn.setBackground(new java.awt.Color(255, 255, 255));
        rightSignIn.setPreferredSize(new java.awt.Dimension(490, 500));

        signInText.setBackground(new java.awt.Color(255, 255, 255));
        signInText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signInText.setForeground(new java.awt.Color(16, 156, 255));
        signInText.setText("Sign Up");

        tkTextSignIn.setBackground(new java.awt.Color(16, 156, 255));
        tkTextSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tkTextSignIn.setForeground(new java.awt.Color(16, 156, 255));
        tkTextSignIn.setText("User name");

        mkTextSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mkTextSignIn.setForeground(new java.awt.Color(16, 156, 255));
        mkTextSignIn.setText("Mật khẩu");

        xnTextSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        xnTextSignIn.setForeground(new java.awt.Color(16, 156, 255));
        xnTextSignIn.setText("Xác nhận mật khẩu");

        msnvTextSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        msnvTextSignIn.setForeground(new java.awt.Color(16, 156, 255));
        msnvTextSignIn.setText("Mã số nhân viên");

        sdtTextSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sdtTextSignIn.setForeground(new java.awt.Color(16, 156, 255));
        sdtTextSignIn.setText("Số điện thoại");

        jButton1.setText("Đăng ký");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        sdtTextSignIn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sdtTextSignIn1.setForeground(new java.awt.Color(16, 156, 255));
        sdtTextSignIn1.setText("email");

        javax.swing.GroupLayout rightSignInLayout = new javax.swing.GroupLayout(rightSignIn);
        rightSignIn.setLayout(rightSignInLayout);
        rightSignInLayout.setHorizontalGroup(
            rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSignInLayout.createSequentialGroup()
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rightSignInLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightSignInLayout.createSequentialGroup()
                                .addComponent(msnvTextSignIn)
                                .addGap(50, 50, 50)
                                .addComponent(inputmkSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSignInLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(inputtkSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(rightSignInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xnTextSignIn)
                        .addGap(258, 258, 258)))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSignInLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(88, 88, 88))
            .addGroup(rightSignInLayout.createSequentialGroup()
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightSignInLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tkTextSignIn)
                            .addComponent(signInText)))
                    .addGroup(rightSignInLayout.createSequentialGroup()
                        .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightSignInLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(sdtTextSignIn1))
                            .addGroup(rightSignInLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mkTextSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sdtTextSignIn))))
                        .addGap(66, 66, 66)
                        .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputmsnvSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputxnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputsdtSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputsdtSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightSignInLayout.setVerticalGroup(
            rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSignInLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(signInText)
                .addGap(39, 39, 39)
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputtkSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkTextSignIn))
                .addGap(24, 24, 24)
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputmkSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msnvTextSignIn))
                .addGap(20, 20, 20)
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputxnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtTextSignIn))
                .addGap(32, 32, 32)
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputmsnvSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtTextSignIn1))
                .addGap(27, 27, 27)
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputsdtSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mkTextSignIn))
                .addGap(27, 27, 27)
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputsdtSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xnTextSignIn))
                .addGroup(rightSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightSignInLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1))
                    .addGroup(rightSignInLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnback)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        backgroundSignIn.add(rightSignIn);
        rightSignIn.setBounds(0, 0, 490, 500);

        leftSignIn.setBackground(new java.awt.Color(16, 155, 255));
        leftSignIn.setPreferredSize(new java.awt.Dimension(310, 500));

        javax.swing.GroupLayout leftSignInLayout = new javax.swing.GroupLayout(leftSignIn);
        leftSignIn.setLayout(leftSignInLayout);
        leftSignInLayout.setHorizontalGroup(
            leftSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        leftSignInLayout.setVerticalGroup(
            leftSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        backgroundSignIn.add(leftSignIn);
        leftSignIn.setBounds(490, 0, 310, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        new giaoDienMoDau().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new dangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundSignIn;
    private javax.swing.JButton btnback;
    private javax.swing.JTextField inputmkSignIn;
    private javax.swing.JTextField inputmsnvSignIn;
    private javax.swing.JTextField inputsdtSignIn;
    private javax.swing.JTextField inputsdtSignIn1;
    private javax.swing.JTextField inputtkSignIn;
    private javax.swing.JTextField inputxnSignIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel leftSignIn;
    private javax.swing.JLabel mkTextSignIn;
    private javax.swing.JLabel msnvTextSignIn;
    private javax.swing.JPanel rightSignIn;
    private javax.swing.JLabel sdtTextSignIn;
    private javax.swing.JLabel sdtTextSignIn1;
    private javax.swing.JLabel signInText;
    private javax.swing.JLabel tkTextSignIn;
    private javax.swing.JLabel xnTextSignIn;
    // End of variables declaration//GEN-END:variables
}
